- name: datatype example
  hosts: local
  connection: local
  vars:
    course: "devsecops" #string
    duration: 4 #number
    topic: #list
    - linux
    - ansible
    - shell
    - aws
    live: true #boolean
    tools: #map
      ci: jenkins
      cloud: aws
      containerisation: docker
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "hello i am learning {{ course }},duration is {{ durtaion}} and the topics are {{ topic }}, tools covered are {{ tools}}, is it live {{ live }}"