- name: convert list into map
  hosts: local
  connection: local
  vars:
    course:
      - {'key': 'name', 'value': 'devsecops'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'status', 'value': 'explained'}
  tasks:
  - name: list to map
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"

  - name: convert lower to upper
    vars:
      name: riya
    ansible.builtin.debug:
      msg: "hello {{ name | lower }}"

  - name: convert lower to upper
    vars:
      name: riya
    ansible.builtin.debug:
      msg: "hello {{ name | upper }}"
      
