- name: filters
  hosts: local
  connection: local
  tasks:
  - name: filtering
    ansible.builtin.debug:
      msg: "hello {{ person | default('riya')}}"

  - name: convert string to list
    vars:
      fruits: "apple, banaana,mango" #string
    ansible.builtin.debug:
        msg: "fruits are : {{ fruits | split(',') }}" 

  - name: convert list into map
    vars:
      course:
        name: devsecops
        duration: 10hrs
        status: explained
    ansible.builtin.debug:
      msg : "course info: {{ course | dict2items }}"  
  