- name: package install
  hosts: web
  become: yes
  tasks:
  - name: packages to be install
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'gcc', state: 'present'}
    - { name: 'mysql', state: 'absent'}
    - { name: 'git', state: 'present'}
    - { name: 'zip', state: 'absent'}  
    