- name: variables example
  hosts: local
  connection: local
  vars:
    Greet: hello
    user: riya
  tasks:
  - name: to print a greeting
    vars:
      Greet: hi
      user: cham
    ansible.builtin.debug:
      msg: "{{ Greet }}, {{ user }}"

  - name: to print a greeting
    vars:
      Greet: hihello
      user: cham
    ansible.builtin.debug:
      msg: "{{ Greet }}, {{ user }}"
   
  